import tomatoToast from "../../assets/starters/tomato-toast.jpg";
import noodleSoup from "../../assets/starters/noodle-soup.jpeg";
import pumpkinSoup from "../../assets/starters/pumpkin-soup.jpg";

const menu = [
    {
        name: "Starters",
        dishes: [
            {
                name: "Tomato Toast",
                id: "tomato-toast",
                description: "Description",
                imageSrc: tomatoToast,
                price: "29",
                isVegan: true,
                isDishOfTheDay: false,
                onSale: false,
                oldPrice: "none",
            },
            {
                name: "Noodle Soup",
                id: "noodle-soup",
                description: "Description",
                imageSrc: noodleSoup,
                price: "5",
                isVegan: false,
                isDishOfTheDay: false,
                onSale: true,
                oldPrice: "8",
            },
            {
                name: "Pumpkin Soup",
                id: "pumpkin-soup",
                description: "Description",
                imageSrc: pumpkinSoup,
                price: "5",
                isVegan: false,
                isDishOfTheDay: true,
                onSale: false,
                oldPrice: "none",
            },
        ],
    },
    {
        name: "Breakfast",
        dishes: [
            {
                name: "Tomato Toast",
                id: "tomato-toast",
                description: "Description",
                imageSrc: tomatoToast,
                price: "29",
                isVegan: true,
                isDishOfTheDay: false,
                onSale: false,
                oldPrice: "none",
            },
            {
                name: "Noodle Soup",
                id: "noodle-soup",
                description: "Description",
                imageSrc: noodleSoup,
                price: "5",
                isVegan: false,
                isDishOfTheDay: false,
                onSale: true,
                oldPrice: "8",
            },
            {
                name: "Pumpkin Soup",
                id: "pumpkin-soup",
                description: "Description",
                imageSrc: pumpkinSoup,
                price: "5",
                isVegan: false,
                isDishOfTheDay: true,
                onSale: false,
                oldPrice: "none",
            },
        ],
    },
    {
        name: "Dinner",
        dishes: [
            {
                name: "Tomato Toast",
                id: "tomato-toast",
                description: "Description",
                imageSrc: tomatoToast,
                price: "29",
                isVegan: true,
                isDishOfTheDay: false,
                onSale: false,
                oldPrice: "none",
            },
            {
                name: "Noodle Soup",
                id: "noodle-soup",
                description: "Description",
                imageSrc: noodleSoup,
                price: "5",
                isVegan: false,
                isDishOfTheDay: false,
                onSale: true,
                oldPrice: "8",
            },
            {
                name: "Pumpkin Soup",
                id: "pumpkin-soup",
                description: "Description",
                imageSrc: pumpkinSoup,
                price: "5",
                isVegan: false,
                isDishOfTheDay: true,
                onSale: false,
                oldPrice: "none",
            },
        ],
    },
    {
        name: "Wine",
        dishes: [
            {
                name: "Tomato Toast",
                id: "tomato-toast",
                description: "Description",
                imageSrc: tomatoToast,
                price: "29",
                isVegan: true,
                isDishOfTheDay: false,
                onSale: false,
                oldPrice: "none",
            },
            {
                name: "Noodle Soup",
                id: "noodle-soup",
                description: "Description",
                imageSrc: noodleSoup,
                price: "5",
                isVegan: false,
                isDishOfTheDay: false,
                onSale: true,
                oldPrice: "8",
            },
            {
                name: "Pumpkin Soup",
                id: "pumpkin-soup",
                description: "Description",
                imageSrc: pumpkinSoup,
                price: "5",
                isVegan: false,
                isDishOfTheDay: true,
                onSale: false,
                oldPrice: "none",
            },
        ],
    },
    {
        name: "Drinks",
        dishes: [
            {
                name: "Tomato Toast",
                id: "tomato-toast",
                description: "Description",
                imageSrc: tomatoToast,
                price: "29",
                isVegan: true,
                isDishOfTheDay: false,
                onSale: false,
                oldPrice: "none",
            },
            {
                name: "Noodle Soup",
                id: "noodle-soup",
                description: "Description",
                imageSrc: noodleSoup,
                price: "5",
                isVegan: false,
                isDishOfTheDay: false,
                onSale: true,
                oldPrice: "8",
            },
            {
                name: "Pumpkin Soup",
                id: "pumpkin-soup",
                description: "Description",
                imageSrc: pumpkinSoup,
                price: "5",
                isVegan: false,
                isDishOfTheDay: true,
                onSale: false,
                oldPrice: "none",
            },
        ],
    },
];

export default menu;
